# Generated by Django 4.0.2 on 2022-03-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('applicant', models.BooleanField(default=True, verbose_name='Solicitante')),
                ('employer', models.BooleanField(default=False, verbose_name='Empleador')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
    ]
